name: Convert and Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  convert_and_package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install marked jszip

      - name: Convert Markdown to HTML
        run: |
          npx marked -o news.html news.md
          npx marked -o changelog.html changelog.md

      - name: Create JSON file
        run: |
          echo '{ "news": "' > release.json
          cat news.html | sed 's/"/\\"/g' >> release.json
          echo '", "changelog": "' >> release.json
          cat changelog.html | sed 's/"/\\"/g' >> release.json
          echo '" }' >> release.json

      - name: Create ZIP archive
        run: |
          zip release.zip release.json

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-zip
          path: release.zip