name: Convert and Package

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write
  
jobs:
  convert_and_package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm init -y
          npm install markdown-it jszip

      - name: Create conversion script
        run: |
          cat > convert.js << 'EOF'
          const fs = require('fs');
          const MarkdownIt = require('markdown-it');
          const JSZip = require('jszip');
          const md = new MarkdownIt();

          const news = md.render(fs.readFileSync('news.md', 'utf8'));
          const changelog = md.render(fs.readFileSync('changelog.md', 'utf8'));

          const data = {
            news: news,
            changelog: changelog
          };

          fs.writeFileSync('release.json', JSON.stringify(data));

          const zip = new JSZip();
          zip.file('release.json', fs.readFileSync('release.json'));
          zip.generateNodeStream({ type: 'nodebuffer', streamFiles: true })
            .pipe(fs.createWriteStream('release.zip'));
          EOF

      - name: Convert and package files
        run: node convert.js

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}